/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashWorkersRouteImport } from './routes/dash/workers'
import { Route as DashLoginRouteImport } from './routes/dash/login'
import { Route as DashListsRouteImport } from './routes/dash/lists'
import { Route as DashListsIndexRouteImport } from './routes/dash/lists/index'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashWorkersRoute = DashWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashRoute,
} as any)
const DashLoginRoute = DashLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashRoute,
} as any)
const DashListsRoute = DashListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => DashRoute,
} as any)
const DashListsIndexRoute = DashListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashListsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dash': typeof DashRouteWithChildren
  '/dash/lists': typeof DashListsRouteWithChildren
  '/dash/login': typeof DashLoginRoute
  '/dash/workers': typeof DashWorkersRoute
  '/dash/': typeof DashIndexRoute
  '/dash/lists/': typeof DashListsIndexRoute
}
export interface FileRoutesByTo {
  '/dash/login': typeof DashLoginRoute
  '/dash/workers': typeof DashWorkersRoute
  '/dash': typeof DashIndexRoute
  '/dash/lists': typeof DashListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dash': typeof DashRouteWithChildren
  '/dash/lists': typeof DashListsRouteWithChildren
  '/dash/login': typeof DashLoginRoute
  '/dash/workers': typeof DashWorkersRoute
  '/dash/': typeof DashIndexRoute
  '/dash/lists/': typeof DashListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dash'
    | '/dash/lists'
    | '/dash/login'
    | '/dash/workers'
    | '/dash/'
    | '/dash/lists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/dash/login' | '/dash/workers' | '/dash' | '/dash/lists'
  id:
    | '__root__'
    | '/dash'
    | '/dash/lists'
    | '/dash/login'
    | '/dash/workers'
    | '/dash/'
    | '/dash/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/workers': {
      id: '/dash/workers'
      path: '/workers'
      fullPath: '/dash/workers'
      preLoaderRoute: typeof DashWorkersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/login': {
      id: '/dash/login'
      path: '/login'
      fullPath: '/dash/login'
      preLoaderRoute: typeof DashLoginRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/lists': {
      id: '/dash/lists'
      path: '/lists'
      fullPath: '/dash/lists'
      preLoaderRoute: typeof DashListsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/lists/': {
      id: '/dash/lists/'
      path: '/'
      fullPath: '/dash/lists/'
      preLoaderRoute: typeof DashListsIndexRouteImport
      parentRoute: typeof DashListsRoute
    }
  }
}

interface DashListsRouteChildren {
  DashListsIndexRoute: typeof DashListsIndexRoute
}

const DashListsRouteChildren: DashListsRouteChildren = {
  DashListsIndexRoute: DashListsIndexRoute,
}

const DashListsRouteWithChildren = DashListsRoute._addFileChildren(
  DashListsRouteChildren,
)

interface DashRouteChildren {
  DashListsRoute: typeof DashListsRouteWithChildren
  DashLoginRoute: typeof DashLoginRoute
  DashWorkersRoute: typeof DashWorkersRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashListsRoute: DashListsRouteWithChildren,
  DashLoginRoute: DashLoginRoute,
  DashWorkersRoute: DashWorkersRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
