services:
  stremthru:
    image: muniftanjim/stremthru
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
  redis:
    image: redis:7-alpine
    ports:
      - 8089:6379
