package ptt

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPTT(t *testing.T) {
	for _, tc := range []struct {
		ttitle string
		result Result
	}{
		{"sons.of.anarchy.s05e10.480p.BluRay.x264-GAnGSteR", Result{
			Title:      "sons of anarchy",
			Resolution: "480p",
			Seasons:    []int{5},
			Episodes:   []int{10},
			Quality:    "BluRay",
			Codec:      "x264",
			Group:      "GAnGSteR",
		}},
		{"Color.Of.Night.Unrated.DC.VostFR.BRrip.x264", Result{
			Title:     "Color Of Night",
			Unrated:   true,
			Languages: []string{"french"},
			Quality:   "BRRip",
			Codec:     "x264",
		}},
		{"Da Vinci Code DVDRip", Result{
			Title:   "Da Vinci Code",
			Quality: "DVDRip",
		}},
		{"Some.girls.1998.DVDRip", Result{
			Title:   "Some girls",
			Quality: "DVDRip",
			Year:    "1998",
		}},
		{"Ecrit.Dans.Le.Ciel.1954.MULTI.DVDRIP.x264.AC3-gismo65", Result{
			Title:     "Ecrit Dans Le Ciel",
			Quality:   "DVDRip",
			Year:      "1954",
			Languages: []string{"multi audio"},
			Dubbed:    true,
			Codec:     "x264",
			Audio:     []string{"AC3"},
			Group:     "gismo65",
		}},
		{"2019 After The Fall Of New York 1983 REMASTERED BDRip x264-GHOULS", Result{
			Title:      "2019 After The Fall Of New York",
			Quality:    "BDRip",
			Edition:    "Remastered",
			Remastered: true,
			Year:       "1983",
			Codec:      "x264",
			Group:      "GHOULS",
		}},
		{"Ghost In The Shell 2017 720p HC HDRip X264 AC3-EVO", Result{
			Title:      "Ghost In The Shell",
			Quality:    "HDRip",
			Hardcoded:  true,
			Year:       "2017",
			Resolution: "720p",
			Codec:      "x264",
			Audio:      []string{"AC3"},
			Group:      "EVO",
		}},
		{"Rogue One 2016 1080p BluRay x264-SPARKS", Result{
			Title:      "Rogue One",
			Quality:    "BluRay",
			Year:       "2016",
			Resolution: "1080p",
			Codec:      "x264",
			Group:      "SPARKS",
		}},
		{"Desperation 2006 Multi Pal DvdR9-TBW1973", Result{
			Title:     "Desperation",
			Quality:   "DVD",
			Year:      "2006",
			Languages: []string{"multi audio"},
			Dubbed:    true,
			Region:    "R9",
			Group:     "TBW1973",
		}},
		{"Maman, j'ai raté l'avion 1990 VFI 1080p BluRay DTS x265-HTG", Result{
			Title:      "Maman, j'ai raté l'avion",
			Quality:    "BluRay",
			Year:       "1990",
			Audio:      []string{"DTS Lossy"},
			Resolution: "1080p",
			Languages:  []string{"french"},
			Codec:      "x265",
			Group:      "HTG",
		}},
		{"Game of Thrones - The Complete Season 3 [HDTV]", Result{
			Title:    "Game of Thrones",
			Seasons:  []int{3},
			Quality:  "HDTV",
			Complete: true,
		}},
		{"The Sopranos: The Complete Series (Season 1,2,3,4,5&6) + Extras", Result{
			Title:    "The Sopranos",
			Seasons:  []int{1, 2, 3, 4, 5, 6},
			Complete: true,
		}},
		{"Skins Season S01-S07 COMPLETE UK Soundtrack 720p WEB-DL", Result{
			Title:      "Skins",
			Seasons:    []int{1, 2, 3, 4, 5, 6, 7},
			Resolution: "720p",
			Quality:    "WEB-DL",
			Complete:   true,
		}},
		{"Futurama.COMPLETE.S01-S07.720p.BluRay.x265-HETeam", Result{
			Title:      "Futurama",
			Seasons:    []int{1, 2, 3, 4, 5, 6, 7},
			Resolution: "720p",
			Quality:    "BluRay",
			Codec:      "x265",
			Group:      "HETeam",
			Complete:   true,
		}},
		{"You.[Uncut].S01.SweSub.1080p.x264-Justiso", Result{
			Title:      "You",
			Edition:    "Uncut",
			Seasons:    []int{1},
			Languages:  []string{"swedish"},
			Resolution: "1080p",
			Codec:      "x264",
			Group:      "Justiso",
		}},
		{"Stephen Colbert 2019 10 25 Eddie Murphy 480p x264-mSD [eztv]", Result{
			Title:      "Stephen Colbert",
			Date:       "2019-10-25",
			Resolution: "480p",
			Codec:      "x264",
		}},
		{"House MD Season 7 Complete MKV", Result{
			Title:     "House MD",
			Seasons:   []int{7},
			Container: "mkv",
			Complete:  true,
		}},
		{"2008 The Incredible Hulk Feature Film.mp4", Result{
			Title:     "The Incredible Hulk Feature Film",
			Year:      "2008",
			Container: "mp4",
			Extension: "mp4",
		}},
		{"【4月/悠哈璃羽字幕社】[UHA-WINGS][不要输！恶之军团][Makeruna!! Aku no Gundan!][04][1080p AVC_AAC][简繁外挂][sc_tc]", Result{
			Title:      "Makeruna!! Aku no Gundan!",
			Episodes:   []int{4},
			Resolution: "1080p",
			Codec:      "avc",
			Audio:      []string{"AAC"},
			Languages:  []string{"chinese"},
		}},
		{"[GM-Team][国漫][西行纪之集结篇][The Westward Ⅱ][2019][17][AVC][GB][1080P]", Result{
			Title:      "The Westward Ⅱ",
			Year:       "2019",
			Episodes:   []int{17},
			Resolution: "1080p",
			Codec:      "avc",
			Group:      "GM-Team",
			Languages:  []string{"chinese"},
		}},
		{"Черное зеркало / Black Mirror / Сезон 4 / Серии 1-6 (6) [2017, США, WEBRip 1080p] MVO + Eng Sub", Result{
			Title:      "Black Mirror",
			Year:       "2017",
			Seasons:    []int{4},
			Episodes:   []int{1, 2, 3, 4, 5, 6},
			Languages:  []string{"english", "russian"},
			Resolution: "1080p",
			Quality:    "WEBRip",
			Subbed:     true,
		}},
		{"[neoHEVC] Student Council's Discretion / Seitokai no Ichizon [Season 1} [BD 1080p x265 HEVC AAC]", Result{
			Title:      "Student Council's Discretion / Seitokai no Ichizon",
			Seasons:    []int{1},
			Resolution: "1080p",
			Quality:    "BDRip",
			Audio:      []string{"AAC"},
			Codec:      "hevc",
			Group:      "neoHEVC",
		}},
		{"[Commie] Chihayafuru 3 - 21 [BD 720p AAC] [5F1911ED].mkv", Result{
			Title:       "Chihayafuru 3",
			Episodes:    []int{21},
			Resolution:  "720p",
			Quality:     "BDRip",
			Audio:       []string{"AAC"},
			Container:   "mkv",
			Extension:   "mkv",
			EpisodeCode: "5F1911ED",
			Group:       "Commie",
		}},
		{"[DVDRip-ITA]The Fast and the Furious: Tokyo Drift [CR-Bt]", Result{
			Title:     "The Fast and the Furious: Tokyo Drift",
			Quality:   "DVDRip",
			Languages: []string{"italian"},
		}},
		{"[BluRay Rip 720p ITA AC3 - ENG AC3 SUB] Hostel[2005]-LIFE[ultimafrontiera]", Result{
			Title:      "Hostel",
			Year:       "2005",
			Resolution: "720p",
			Quality:    "BRRip",
			Audio:      []string{"AC3"},
			Languages:  []string{"english", "italian"},
			Group:      "LIFE",
			Subbed:     true,
		}},
		{"[OFFICIAL ENG SUB] Soul Land Episode 121-125 [1080p][Soft Sub][Web-DL][Douluo Dalu][斗罗大陆]", Result{
			Title:      "Soul Land",
			Episodes:   []int{121, 122, 123, 124, 125},
			Resolution: "1080p",
			Quality:    "WEB-DL",
			Languages:  []string{"english", "chinese"},
			Subbed:     true,
		}},
		{"[720p] The God of Highschool Season 1", Result{
			Title:      "The God of Highschool",
			Seasons:    []int{1},
			Resolution: "720p",
		}},
		{"Heidi Audio Latino DVDRip [cap. 3 Al 18}", Result{
			Title:     "Heidi",
			Episodes:  []int{3},
			Quality:   "DVDRip",
			Languages: []string{"latino"},
		}},
		{"Sprint.2024.S01.COMPLETE.1080p.WEB.h264-EDITH[TGx]", Result{
			Title:      "Sprint",
			Year:       "2024",
			Seasons:    []int{1},
			Quality:    "WEB",
			Resolution: "1080p",
			Codec:      "h264",
			Group:      "EDITH",
			Complete:   true,
		}},
		{"High Heat *2022* [BRRip.XviD] Lektor PL", Result{
			Title:     "High Heat",
			Year:      "2022",
			Codec:     "xvid",
			Quality:   "BRRip",
			Languages: []string{"polish"},
		}},
		{"Ghost Busters *1984-2021* [720p] [BDRip] [AC-3] [XviD] [Lektor + Dubbing PL] [DYZIO]", Result{
			Title:      "Ghost Busters",
			Year:       "1984-2021",
			Resolution: "720p",
			Audio:      []string{"AC3"},
			Codec:      "xvid",
			Complete:   true,
			Quality:    "BDRip",
			Languages:  []string{"polish"},
		}},
		{"20-20.2024.11.15.Fatal.Disguise.XviD-AFG[EZTVx.to].avi", Result{
			Title:     "20-20",
			Date:      "2024-11-15",
			Codec:     "xvid",
			Quality:   "XviD",
			Group:     "AFG",
			Container: "avi",
			Extension: "avi",
			Site:      "EZTVx.to",
		}},
	} {
		t.Run(tc.ttitle, func(t *testing.T) {
			result := Parse(tc.ttitle)
			assert.Equal(t, &tc.result, result)
		})
	}

	intRange := func(start, end int) []int {
		nums := make([]int, end-start+1)
		for i := range end - start + 1 {
			nums[i] = start + i
		}
		return nums
	}

	// PY
	for _, tc := range []struct {
		ttitle string
		result Result
	}{
		{"sons.of.anarchy.s05e10.480p.BluRay.x264-GAnGSteR", Result{
			Title:      "sons of anarchy",
			Resolution: "480p",
			Seasons:    []int{5},
			Episodes:   []int{10},
			Quality:    "BluRay",
			Codec:      "x264",
			Group:      "GAnGSteR",
		}},
		{"Color.Of.Night.Unrated.DC.VostFR.BRrip.x264", Result{
			Title:     "Color Of Night",
			Unrated:   true,
			Languages: []string{"french"},
			Quality:   "BRRip",
			Codec:     "x264",
		}},
		{"Da Vinci Code DVDRip", Result{
			Title:   "Da Vinci Code",
			Quality: "DVDRip",
		}},
		{"Some.girls.1998.DVDRip", Result{
			Title:   "Some girls",
			Quality: "DVDRip",
			Year:    "1998",
		}},
		{"Ecrit.Dans.Le.Ciel.1954.MULTI.DVDRIP.x264.AC3-gismo65", Result{
			Title:     "Ecrit Dans Le Ciel",
			Quality:   "DVDRip",
			Languages: []string{"multi audio"},
			Year:      "1954",
			Dubbed:    true,
			Codec:     "x264",
			Audio:     []string{"AC3"},
			Group:     "gismo65",
		}},
		{"2019 After The Fall Of New York 1983 REMASTERED BDRip x264-GHOULS", Result{
			Title:      "2019 After The Fall Of New York",
			Quality:    "BDRip",
			Edition:    "Remastered",
			Remastered: true,
			Year:       "1983",
			Codec:      "x264",
			Group:      "GHOULS",
		}},
		{"Ghost In The Shell 2017 720p HC HDRip X264 AC3-EVO", Result{
			Title:      "Ghost In The Shell",
			Quality:    "HDRip",
			Hardcoded:  true,
			Year:       "2017",
			Resolution: "720p",
			Codec:      "x264",
			Audio:      []string{"AC3"},
			Group:      "EVO",
		}},
		{"Rogue One 2016 1080p BluRay x264-SPARKS", Result{
			Title:      "Rogue One",
			Quality:    "BluRay",
			Year:       "2016",
			Resolution: "1080p",
			Codec:      "x264",
			Group:      "SPARKS",
		}},
		{"Desperation 2006 Multi Pal DvdR9-TBW1973", Result{
			Title:     "Desperation",
			Languages: []string{"multi audio"},
			Quality:   "DVD",
			Year:      "2006",
			Dubbed:    true,
			Region:    "R9",
			Group:     "TBW1973",
		}},
		{"Maman, j'ai raté l'avion 1990 VFI 1080p BluRay DTS x265-HTG", Result{
			Title:      "Maman, j'ai raté l'avion",
			Quality:    "BluRay",
			Year:       "1990",
			Audio:      []string{"DTS Lossy"},
			Resolution: "1080p",
			Languages:  []string{"french"},
			Codec:      "x265",
			Group:      "HTG",
		}},
		{"Game of Thrones - The Complete Season 3 [HDTV]", Result{
			Title:    "Game of Thrones",
			Seasons:  []int{3},
			Quality:  "HDTV",
			Complete: true,
		}},
		{"The Sopranos: The Complete Series { Season 1,2,3,4,5&6 } + Extras", Result{
			Title:    "The Sopranos",
			Seasons:  []int{1, 2, 3, 4, 5, 6},
			Complete: true,
		}},
		{"Skins Season S01-S07 COMPLETE UK Soundtrack 720p WEB-DL", Result{
			Seasons: []int{1, 2, 3, 4, 5, 6, 7},
			Title:   "Skins",
			// "country":  "UK",
			Resolution: "720p",
			Quality:    "WEB-DL",
			Complete:   true,
		}},
		{"Futurama.COMPLETE.S01-S07.720p.BluRay.x265-HETeam", Result{
			Title:      "Futurama",
			Seasons:    []int{1, 2, 3, 4, 5, 6, 7},
			Resolution: "720p",
			Quality:    "BluRay",
			Codec:      "x265",
			Group:      "HETeam",
			Complete:   true,
		}},
		{"You.[Uncut].S01.SweSub.1080p.x264-Justiso", Result{
			Title:      "You",
			Edition:    "Uncut",
			Seasons:    []int{1},
			Languages:  []string{"swedish"},
			Resolution: "1080p",
			Codec:      "x264",
			Group:      "Justiso",
		}},
		{"Stephen Colbert 2019 10 25 Eddie Murphy 480p x264-mSD [eztv]", Result{
			Title:      "Stephen Colbert",
			Date:       "2019-10-25",
			Resolution: "480p",
			Codec:      "x264",
		}},
		{"House MD Season 7 Complete MKV", Result{
			Title:     "House MD",
			Seasons:   []int{7},
			Container: "mkv",
			Complete:  true,
		}},
		{"2008 The Incredible Hulk Feature Film.mp4", Result{
			Title:     "The Incredible Hulk Feature Film",
			Year:      "2008",
			Container: "mp4",
			Extension: "mp4",
		}},
		{"【4月/悠哈璃羽字幕社】[UHA-WINGS][不要输！恶之军团][Makeruna!! Aku no Gundan!][04][1080p AVC_AAC][简繁外挂][sc_tc]", Result{
			Title:      "Makeruna!! Aku no Gundan!",
			Episodes:   []int{4},
			Resolution: "1080p",
			Codec:      "avc",
			Audio:      []string{"AAC"},
			Languages:  []string{"chinese"},
		}},
		{"[GM-Team][国漫][西行纪之集结篇][The Westward Ⅱ][2019][17][AVC][GB][1080P]", Result{
			Title:      "The Westward Ⅱ",
			Year:       "2019",
			Episodes:   []int{17},
			Resolution: "1080p",
			Codec:      "avc",
			Group:      "GM-Team",
			Languages:  []string{"chinese"},
		}},
		{"Черное зеркало / Black Mirror / Сезон 4 / Серии 1-6 { 6 } [2017, США, WEBRip 1080p] MVO + Eng Sub", Result{
			Title:      "Black Mirror",
			Year:       "2017",
			Seasons:    []int{4},
			Episodes:   []int{1, 2, 3, 4, 5, 6},
			Languages:  []string{"english", "russian"},
			Resolution: "1080p",
			Quality:    "WEBRip",
			Subbed:     true,
		}},
		{"[neoHEVC] Student Council's Discretion / Seitokai no Ichizon [Season 1] [BD 1080p x265 HEVC AAC]", Result{
			Title:      "Student Council's Discretion / Seitokai no Ichizon",
			Seasons:    []int{1},
			Resolution: "1080p",
			Quality:    "BDRip",
			Audio:      []string{"AAC"},
			Codec:      "hevc",
			Group:      "neoHEVC",
		}},
		{"[Commie] Chihayafuru 3 - 21 [BD 720p AAC] [5F1911ED].mkv", Result{
			Title:       "Chihayafuru 3",
			Episodes:    []int{21},
			Resolution:  "720p",
			Quality:     "BDRip",
			Audio:       []string{"AAC"},
			Container:   "mkv",
			Extension:   "mkv",
			EpisodeCode: "5F1911ED",
			Group:       "Commie",
		}},
		{"[DVDRip-ITA]The Fast and the Furious: Tokyo Drift [CR-Bt]", Result{
			Title:     "The Fast and the Furious: Tokyo Drift",
			Quality:   "DVDRip",
			Languages: []string{"italian"},
		}},
		{"[BluRay Rip 720p ITA AC3 - ENG AC3 SUB] Hostel[2005]-LIFE[ultimafrontiera]", Result{
			Title:      "Hostel",
			Year:       "2005",
			Resolution: "720p",
			Quality:    "BRRip",
			Audio:      []string{"AC3"},
			Languages:  []string{"english", "italian"},
			Group:      "LIFE",
			Subbed:     true,
		}},
		{"[OFFICIAL ENG SUB] Soul Land Episode 121-125 [1080p][Soft Sub][Web-DL][Douluo Dalu][斗罗大陆]", Result{
			Title:      "Soul Land",
			Episodes:   []int{121, 122, 123, 124, 125},
			Languages:  []string{"english", "chinese"},
			Resolution: "1080p",
			Quality:    "WEB-DL",
			Subbed:     true,
		}},
		{"[720p] The God of Highschool Season 1", Result{
			Title:      "The God of Highschool",
			Seasons:    []int{1},
			Resolution: "720p",
		}},
		{"Heidi Audio Latino DVDRip [cap. 3 Al 18]", Result{
			Title:     "Heidi",
			Episodes:  []int{3},
			Quality:   "DVDRip",
			Languages: []string{"latino"},
		}},
		{"Anatomia De Grey - Temporada 19 [HDTV][Castellano][www.AtomoHD.nu].avi", Result{
			Title:     "Anatomia De Grey",
			Seasons:   []int{19},
			Container: "avi",
			Extension: "avi",
			Languages: []string{"spanish"},
			Quality:   "HDTV",
			Site:      "www.AtomoHD.nu",
		}},
		{"Sprint.2024.S01.COMPLETE.1080p.WEB.h264-EDITH[TGx]", Result{
			Title:      "Sprint",
			Year:       "2024",
			Seasons:    []int{1},
			Quality:    "WEB",
			Resolution: "1080p",
			Codec:      "h264",
			Group:      "EDITH",
			Complete:   true,
		}},
		{"Madame Web 2024 UHD BluRay 2160p TrueHD Atmos 7 1 DV HEVC REMUX-FraMeSToR", Result{
			Title:      "Madame Web",
			Year:       "2024",
			Quality:    "BluRay REMUX",
			Resolution: "4k",
			Channels:   []string{"7.1"},
			Audio:      []string{"Atmos", "TrueHD"},
			Codec:      "hevc",
			HDR:        []string{"DV"},
			Group:      "FraMeSToR",
		}},
		{"The.Witcher.US.S01.INTERNAL.1080p.WEB.x264-STRiFE", Result{
			Title:      "The Witcher",
			Seasons:    []int{1},
			Quality:    "WEB",
			Resolution: "1080p",
			Codec:      "x264",
			Group:      "STRiFE",
		}},
		{"Madame Web (2024) 1080p HINDI ENGLISH 10bit AMZN WEBRip DDP5 1 x265 HEVC - PSA Shadow", Result{
			Title:      "Madame Web",
			Year:       "2024",
			Languages:  []string{"english", "hindi"},
			Quality:    "WEBRip",
			Resolution: "1080p",
			BitDepth:   "10bit",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Codec:      "hevc",
			Network:    "Amazon",
		}},
		{"The Simpsons S01E01 1080p BluRay x265 HEVC 10bit AAC 5.1 Tigole", Result{
			Title:      "The Simpsons",
			Seasons:    []int{1},
			Episodes:   []int{1},
			Resolution: "1080p",
			Quality:    "BluRay",
			Codec:      "hevc",
			BitDepth:   "10bit",
			Audio:      []string{"AAC"},
			Channels:   []string{"5.1"},
		}},
		{"[DB]_Bleach_264_[012073FE].avi", Result{
			Title:       "Bleach",
			Container:   "avi",
			Extension:   "avi",
			EpisodeCode: "012073FE",
			Episodes:    []int{264},
			Group:       "DB",
		}},
		{"[SubsPlease] One Piece - 1111 (480p) [2E05E658].mkv", Result{
			Title:       "One Piece",
			Container:   "mkv",
			Resolution:  "480p",
			Extension:   "mkv",
			EpisodeCode: "2E05E658",
			Episodes:    []int{1111},
			Group:       "SubsPlease",
		}},
		{"One Piece S01E1056 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR) mkv", Result{
			Title:      "One Piece",
			Seasons:    []int{1},
			Episodes:   []int{1056},
			Languages:  []string{"french"},
			Container:  "mkv",
			Resolution: "1080p",
			Quality:    "WEB",
			Codec:      "x264",
			Audio:      []string{"AAC"},
		}},
		{"Mary.Poppins.1964.50th.ANNIVERSARY.EDITION.REMUX.1080p.Bluray.AVC.DTS-HD.MA.5.1-LEGi0N", Result{
			Title:      "Mary Poppins",
			Year:       "1964",
			Edition:    "Anniversary Edition",
			Quality:    "BluRay REMUX",
			Resolution: "1080p",
			Audio:      []string{"DTS Lossless"},
			Channels:   []string{"5.1"},
			Codec:      "avc",
			Group:      "LEGi0N",
		}},
		{"The.Lord.of.the.Rings.The.Fellowship.of.the.Ring.2001.EXTENDED.2160p.UHD.BluRay.x265.10bit.HDR.TrueHD.7.1.Atmos-BOREDOR", Result{
			Title:      "The Lord of the Rings The Fellowship of the Ring",
			Year:       "2001",
			Resolution: "4k",
			Edition:    "Extended Edition",
			Extended:   true,
			Quality:    "BluRay",
			Codec:      "x265",
			BitDepth:   "10bit",
			Audio:      []string{"Atmos", "TrueHD"},
			Channels:   []string{"7.1"},
			HDR:        []string{"HDR"},
			Group:      "BOREDOR",
		}},
		{"Escaflowne (2000) (BDRip 1896x1048p x265 HEVC TrueHD, FLACx3, AC3 5.1x2+2.0x3)(Triple Audio)[sxales].mkv", Result{
			Title:      "Escaflowne",
			Year:       "2000",
			Quality:    "BDRip",
			Codec:      "hevc",
			Languages:  []string{"multi audio"},
			Resolution: "1048p",
			Audio:      []string{"TrueHD", "FLAC", "AC3"},
			Channels:   []string{"5.1"},
			// Group:      "sxales",
			Dubbed:    true,
			Container: "mkv",
			Extension: "mkv",
		}},
		{"[www.1TamilMV.pics]_The.Great.Indian.Suicide.2023.Tamil.TRUE.WEB-DL.4K.SDR.HEVC.(DD+5.1.384Kbps.&.AAC).3.2GB.ESub.mkv", Result{
			Title:      "The Great Indian Suicide",
			Year:       "2023",
			Languages:  []string{"english", "tamil"},
			Quality:    "WEB-DL",
			Resolution: "4k",
			HDR:        []string{"SDR"},
			Codec:      "hevc",
			Site:       "www.1TamilMV.pics",
			Size:       "3.2GB",
			Container:  "mkv",
			Extension:  "mkv",
			// "bitrate":   "384kbps",
			Audio:    []string{"TrueHD", "DDP", "AAC"},
			Channels: []string{"5.1"},
		}},
		{"www.5MovieRulz.show - Khel Khel Mein (2024) 1080p Hindi DVDScr - x264 - AAC - 2.3GB.mkv", Result{
			Title:      "Khel Khel Mein",
			Year:       "2024",
			Languages:  []string{"hindi"},
			Quality:    "SCR",
			Codec:      "x264",
			Audio:      []string{"AAC"},
			Resolution: "1080p",
			Container:  "mkv",
			Extension:  "mkv",
			Size:       "2.3GB",
			Site:       "www.5MovieRulz.show",
		}},
		{"超能警探.Memorist.S01E01.2160p.WEB-DL.H265.AAC-FLTTH.mkv", Result{
			Title:      "Memorist",
			Seasons:    []int{1},
			Episodes:   []int{1},
			Languages:  []string{"chinese"},
			Quality:    "WEB-DL",
			Codec:      "h265",
			Audio:      []string{"AAC"},
			Resolution: "4k",
			Container:  "mkv",
			Extension:  "mkv",
			Group:      "FLTTH",
		}},
		{"Futurama.S08E03.How.the.West.Was.1010001.1080p.HULU.WEB-DL.DDP5.1.H.264-FLUX.mkv", Result{
			Title:      "Futurama",
			Seasons:    []int{8},
			Episodes:   []int{3},
			Network:    "Hulu",
			Codec:      "h264",
			Container:  "mkv",
			Extension:  "mkv",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Quality:    "WEB-DL",
			Resolution: "1080p",
			Group:      "FLUX",
		}},
		{"V.H.S.2 [2013] 1080p BDRip x265 DTS-HD MA 5.1 Kira [SEV].mkv", Result{
			Title:      "V H S 2",
			Year:       "2013",
			Quality:    "BDRip",
			Codec:      "x265",
			Audio:      []string{"DTS Lossless"},
			Channels:   []string{"5.1"},
			Container:  "mkv",
			Extension:  "mkv",
			Resolution: "1080p",
		}},
		{"{WWW.BLUDV.TV} Love, Death & Robots - 1ª Temporada Completa 2019 (1080p) Acesse o ORIGINAL WWW.BLUDV.TV", Result{
			Title:      "Love, Death & Robots",
			Seasons:    []int{1},
			Languages:  []string{"spanish"},
			Resolution: "1080p",
			Year:       "2019",
			Complete:   true,
			Site:       "WWW.BLUDV.TV",
		}},
		{"www.MovCr.to - Bikram Yogi, Guru, Predator (2019) 720p WEB_DL x264 ESubs [Dual Audio]-[Hindi + Eng] - 950MB - MovCr.mkv", Result{
			Title:      "Bikram Yogi, Guru, Predator",
			Year:       "2019",
			Languages:  []string{"dual audio", "english", "hindi"},
			Quality:    "WEB-DL",
			Resolution: "720p",
			Codec:      "x264",
			Container:  "mkv",
			Extension:  "mkv",
			Site:       "www.MovCr.to",
			Dubbed:     true,
			Group:      "MovCr",
			Size:       "950MB",
		}},
		{"28.days.2000.1080p.bluray.x264-mimic.mkv", Result{
			Title:      "28 days",
			Year:       "2000",
			Resolution: "1080p",
			Quality:    "BluRay",
			Codec:      "x264",
			Container:  "mkv",
			Extension:  "mkv",
			Group:      "mimic",
		}},
		{"4.20.Massacre.2018.1080p.BluRay.x264.AAC-[YTS.MX].mp4", Result{
			Title:      "4 20 Massacre",
			Year:       "2018",
			Resolution: "1080p",
			Quality:    "BluRay",
			Codec:      "x264",
			Audio:      []string{"AAC"},
			Container:  "mp4",
			Extension:  "mp4",
			Site:       "YTS.MX",
		}},
		{"inside.out.2.2024.d.ru.ua.ts.1o8op.mkv", Result{
			Title: "inside out 2",
			Year:  "2024",
			// Resolution: "1080p", //- this is correct. we dont want it to parse the resolution here.
			Quality:   "TeleSync",
			Container: "mkv",
			Extension: "mkv",
			Languages: []string{"russian"},
		}},
		{"I.S.S.2023.P.WEB-DL.1O8Op.mkv", Result{
			Title:     "I S S",
			Year:      "2023",
			Quality:   "WEB-DL",
			Container: "mkv",
			Extension: "mkv",
		}},
		{"Skazka.2022.Pa.WEB-DL.1O8Op.mkv", Result{
			Title:     "Skazka",
			Year:      "2022",
			Quality:   "WEB-DL",
			Container: "mkv",
			Extension: "mkv",
		}},
		{"Spider-Man.Across.the.Spider-Verse.2023.Dt.WEBRip.1O8Op.mkv", Result{
			Title:     "Spider-Man Across the Spider-Verse",
			Year:      "2023",
			Quality:   "WEBRip",
			Container: "mkv",
			Extension: "mkv",
		}},
		{"Civil.War.2024.D.WEB-DL.1O8Op.mkv", Result{
			Title:     "Civil War",
			Year:      "2024",
			Quality:   "WEB-DL",
			Container: "mkv",
			Extension: "mkv",
		}},
		{"Dune.Part.Two.2024.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX[TGx]", Result{
			Title:      "Dune Part Two",
			Year:       "2024",
			Resolution: "4k",
			Quality:    "WEB-DL",
			Codec:      "h265",
			Audio:      []string{"DDP", "Atmos"},
			Channels:   []string{"5.1"},
			Group:      "FLUX",
			HDR:        []string{"DV", "HDR"},
		}},
		{"Saw.3D.2010.1080p.ITA-ENG.BluRay.x265.AAC-V3SP4EV3R.mkv", Result{
			Title:      "Saw 3D",
			Year:       "2010",
			Languages:  []string{"english", "italian"},
			Resolution: "1080p",
			Quality:    "BluRay",
			Codec:      "x265",
			Audio:      []string{"AAC"},
			Container:  "mkv",
			Extension:  "mkv",
			Group:      "V3SP4EV3R",
		}},
		{"Dead Before Dawn 3D (2012) [3D.BLU-RAY] [1080p 3D] [BluRay] [HSBS] [YTS.MX]", Result{
			Title:      "Dead Before Dawn",
			Year:       "2012",
			Resolution: "1080p",
			Quality:    "BluRay",
			ThreeD:     "3D HSBS",
		}},
		{"Wonder.Woman.1984.2020.3D.1080p.BluRay.x264-SURCODE[rarbg]", Result{
			Title:      "Wonder Woman 1984",
			Year:       "2020",
			Resolution: "1080p",
			Quality:    "BluRay",
			Codec:      "x264",
			Group:      "SURCODE",
			ThreeD:     "3D",
		}},
		{"The.Last.of.Us.S01E08.1080p.WEB.H264-CAKES[TGx]", Result{
			Title:      "The Last of Us",
			Seasons:    []int{1},
			Episodes:   []int{8},
			Resolution: "1080p",
			Quality:    "WEB",
			Codec:      "h264",
			Group:      "CAKES",
		}},
		{"The.Office.UK.S01.1080P.BLURAY.REMUX.AVC.DD5.1-NOGRP", Result{
			Title:      "The Office",
			Seasons:    []int{1},
			Quality:    "BluRay REMUX",
			Resolution: "1080p",
			Audio:      []string{"DD"},
			Channels:   []string{"5.1"},
			Codec:      "avc",
			Group:      "NOGRP",
		}},
		{"The.Office.US.S01-09.COMPLETE.SERIES.1080P.BLURAY.X265-HIQVE", Result{
			Title:      "The Office",
			Seasons:    []int{1, 2, 3, 4, 5, 6, 7, 8, 9},
			Quality:    "BluRay",
			Resolution: "1080p",
			Codec:      "x265",
			Complete:   true,
			Group:      "HIQVE",
		}},
		{"Hard Knocks 2001 S23E01 1080p MAX WEB-DL DDP2 0 x264-NTb[EZTVx.to].mkv", Result{
			Title:      "Hard Knocks",
			Year:       "2001",
			Seasons:    []int{23},
			Episodes:   []int{1},
			Quality:    "WEB-DL",
			Resolution: "1080p",
			Codec:      "x264",
			Audio:      []string{"DDP"},
			// #Channels: []string{"2.0"},
			Group:     "NTb",
			Extension: "mkv",
			Container: "mkv",
			Site:      "EZTVx.to",
		}},
		{"Fallout.S01E03.The.Head.2160p.DV.HDR10Plus.Ai-Enhanced.H265.DDP.5.1.MULTI.RIFE.4.15v2-60fps-DirtyHippie.mkv", Result{
			Title:      "Fallout",
			Seasons:    []int{1},
			Episodes:   []int{3},
			Languages:  []string{"multi audio"},
			Resolution: "4k",
			Codec:      "h265",
			Audio:      []string{"DDP"},
			BitDepth:   "10bit",
			Channels:   []string{"5.1"},
			Group:      "DirtyHippie",
			Container:  "mkv",
			Dubbed:     true,
			Extension:  "mkv",
			HDR:        []string{"DV", "HDR10+"},
			Upscaled:   true,
		}},
		{"BoJack Horseman [06x01-08 of 16] (2019-2020) WEB-DLRip 720p", Result{
			Title:      "BoJack Horseman",
			Seasons:    []int{6},
			Episodes:   []int{1, 2, 3, 4, 5, 6, 7, 8},
			Resolution: "720p",
			Quality:    "WEB-DLRip",
			Complete:   true,
			Year:       "2019-2020",
		}},
		{"Трон: Наследие / TRON: Legacy (2010) WEB-DL 1080p | D | Open Matte", Result{
			Title:      "TRON: Legacy",
			Year:       "2010",
			Languages:  []string{"russian"},
			Resolution: "1080p",
			Quality:    "WEB-DL",
		}},
		{"Wentworth.S08E06.PDTV.AAC2.0.x264-BTN", Result{
			Title:    "Wentworth",
			Seasons:  []int{8},
			Episodes: []int{6},
			Quality:  "PDTV",
			Codec:    "x264",
			Audio:    []string{"AAC"},
			Group:    "BTN",
		}},
		{"www.1Tamilblasters.co - Guardians of the Galaxy Vol. 3 (2023) [4K IMAX UHD HEVC - BDRip - [Tam + Mal + Tel + Hin + Eng] - x264 - DDP5.1 (192Kbps) - 8.3GB - ESub].mkv", Result{
			Title:      "Guardians of the Galaxy Vol. 3",
			Year:       "2023",
			Languages:  []string{"english", "hindi", "telugu", "tamil", "malayalam"},
			Quality:    "BDRip",
			Codec:      "hevc",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Resolution: "4k",
			Container:  "mkv",
			Extension:  "mkv",
			Site:       "www.1Tamilblasters.co",
			Size:       "8.3GB",
			// "bitrate":   "192kbps",
			Edition: "IMAX",
		}},
		{"【高清影视之家发布 www.hdbthd.com】奥本海默 杜比视界版本 高码版 国英多音轨 中文字幕 .oppenheimer.2023.2160p.hq.web-dl.h265.dv.ddp5.1.2audio-dreamhd", Result{
			Title:      "oppenheimer",
			Year:       "2023",
			Languages:  []string{"chinese"},
			Quality:    "WEB-DL",
			Codec:      "h265",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Resolution: "4k",
			Site:       "www.hdbthd.com",
			Group:      "dreamhd",
			HDR:        []string{"DV"},
		}},
		{"Venom (2018) HD-TS 720p Hindi Dubbed (Clean Audio) x264", Result{
			Title:      "Venom",
			Year:       "2018",
			Languages:  []string{"hindi"},
			Quality:    "TeleSync",
			Resolution: "720p",
			Codec:      "x264",
			Audio:      []string{"HQ"},
			Dubbed:     true,
		}},
		{"www.Tamilblasters.party - The Wheel of Time (2021) Season 01 EP(01-08) [720p HQ HDRip - [Tam + Tel + Hin] - DDP5.1 - x264 - 2.7GB - ESubs]", Result{
			Title:      "The Wheel of Time",
			Year:       "2021",
			Seasons:    []int{1},
			Episodes:   []int{1, 2, 3, 4, 5, 6, 7, 8},
			Languages:  []string{"hindi", "telugu", "tamil"},
			Quality:    "HDRip",
			Resolution: "720p",
			Codec:      "x264",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Site:       "www.Tamilblasters.party",
			Size:       "2.7GB",
		}},
		{"The.Walking.Dead.S06E07.SUBFRENCH.HDTV.x264-AMB3R.mkv", Result{
			// # should detect french language and subbed
			Title:     "The Walking Dead",
			Seasons:   []int{6},
			Episodes:  []int{7},
			Languages: []string{"french"},
			Quality:   "HDTV",
			Codec:     "x264",
			Group:     "AMB3R",
			Extension: "mkv",
			Container: "mkv",
		}},
		{"The Walking Dead S05E03 720p Remux x264-ASAP[ettv]", Result{
			Title:      "The Walking Dead",
			Seasons:    []int{5},
			Episodes:   []int{3},
			Quality:    "REMUX",
			Resolution: "720p",
			Codec:      "x264",
			Group:      "ASAP",
		}},
		{"www.TamilBlasters.vip - Shang-Chi (2021) [720p BDRip - [Tamil + Telugu + Hindi + Eng] - x264 - DDP5.1 (192 Kbps) - 1.4GB - ESubs].mkv", Result{
			Title:      "Shang-Chi",
			Year:       "2021",
			Languages:  []string{"english", "hindi", "telugu", "tamil"},
			Quality:    "BDRip",
			Resolution: "720p",
			Codec:      "x264",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Site:       "www.TamilBlasters.vip",
			Size:       "1.4GB",
			Extension:  "mkv",
			Container:  "mkv",
		}},
		{"Game of Thrones 1ª a 8ª Temporada Completa [720p-1080p] [BluRay] [DUAL]", Result{
			Title:      "Game of Thrones",
			Seasons:    []int{1, 2, 3, 4, 5, 6, 7, 8},
			Languages:  []string{"spanish", "dual audio"},
			Resolution: "1080p",
			Quality:    "BluRay",
			Complete:   true,
			Dubbed:     true,
		}},
		{"Kill.2024.REPACK.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-XEBEC.mkv", Result{
			Title:      "Kill",
			Year:       "2024",
			Resolution: "1080p",
			Quality:    "WEB-DL",
			Codec:      "h264",
			Audio:      []string{"DDP", "Atmos"},
			Channels:   []string{"5.1"},
			Group:      "XEBEC",
			Container:  "mkv",
			Extension:  "mkv",
			Network:    "Amazon",
			Repack:     true,
		}},
		{"Mad.Max.Fury.Road.2015.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265[TGx]", Result{
			Title:      "Mad Max Fury Road",
			Year:       "2015",
			Resolution: "1080p",
			Codec:      "x265",
			BitDepth:   "10bit",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Group:      "GalaxyRG265",
			Quality:    "BluRay",
		}},
		{"Властелин колец: Кольца власти (S1E1-8 of 8) / The Lord of the Rings: The Rings of Power (2022) WEB-DL", Result{
			Title:     "Властелин колец: Кольца власти", //# The Lord of the Rings: The Rings of Power  - We probably want the US title instead here
			Year:      "2022",
			Seasons:   []int{1},
			Episodes:  []int{1, 2, 3, 4, 5, 6, 7, 8},
			Languages: []string{"russian"},
			Quality:   "WEB-DL",
		}},
		{"抓娃娃 Successor.2024.TC1080P.国语中字", Result{
			Title:      "Successor",
			Year:       "2024",
			Languages:  []string{"chinese"},
			Resolution: "1080p",
			Quality:    "TeleCine",
		}},
		{"True.Detective.S03E02.720p.WEB.x265-MiNX[eztv].mkv", Result{
			Title:      "True Detective",
			Seasons:    []int{3},
			Episodes:   []int{2},
			Resolution: "720p",
			Quality:    "WEB",
			Codec:      "x265",
			Group:      "MiNX",
			Extension:  "mkv",
			Container:  "mkv",
		}},
		{"True.Grit.1969.720p.WEB.x265-MiNX[eztv].mkv", Result{
			Title:      "True Grit",
			Year:       "1969",
			Resolution: "720p",
			Quality:    "WEB",
			Codec:      "x265",
			Group:      "MiNX",
			Extension:  "mkv",
			Container:  "mkv",
		}},
		{"Free Samples (2012) [BluRay] [1080p] [YTS.AM]", Result{
			Title:      "Free Samples",
			Year:       "2012",
			Resolution: "1080p",
			Quality:    "BluRay",
		}},
		{"Trailer Park Boys S01-S10 + Movies + Specials + Extras [Ultimate Collection]-CAPTAiN", Result{
			Title:    "Trailer Park Boys",
			Seasons:  []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
			Complete: true,
			Group:    "CAPTAiN",
		}},
		{"Adbhut (2024) Hindi 1080p HDTVRip x264 AAC 5.1 [2.2GB] - QRips", Result{
			Title:      "Adbhut",
			Year:       "2024",
			Languages:  []string{"hindi"},
			Resolution: "1080p",
			Quality:    "HDTVRip",
			Codec:      "x264",
			Audio:      []string{"AAC"},
			Channels:   []string{"5.1"},
			Group:      "QRips",
			Size:       "2.2GB",
		}},
		{"Blood Diamond (2006) 1080p BluRay H264 DolbyD 5 1 + nickarad mp4", Result{
			Title:      "Blood Diamond",
			Year:       "2006",
			Resolution: "1080p",
			Quality:    "BluRay",
			Codec:      "h264",
			Audio:      []string{"DD"},
			Channels:   []string{"5.1"},
			Container:  "mp4",
		}},
		{"The Lockerbie Bombing (2013) Documentary HDTVRIP", Result{
			Title:       "The Lockerbie Bombing",
			Year:        "2013",
			Documentary: true,
			Quality:     "HDTVRip",
		}},
		{"STEVE.martin.a.documentary.in.2.pieces.S01.COMPLETE.1080p.WEB.H264-SuccessfulCrab[TGx]", Result{
			Title:       "STEVE martin a documentary in 2 pieces",
			Seasons:     []int{1},
			Quality:     "WEB",
			Codec:       "h264",
			Group:       "SuccessfulCrab",
			Resolution:  "1080p",
			Documentary: true,
			Complete:    true,
		}},
		{"The New Frontier S01E10 720p WEB H264-INFLATE[eztv] mkv", Result{
			Title:      "The New Frontier",
			Seasons:    []int{1},
			Episodes:   []int{10},
			Quality:    "WEB",
			Container:  "mkv",
			Codec:      "h264",
			Group:      "INFLATE",
			Resolution: "720p",
		}},
		{"[BEST-TORRENTS.COM] The.Penguin.S01E07.MULTi.1080p.AMZN.WEB-DL.H264.DDP5.1.Atmos-K83", Result{
			Title:      "The Penguin",
			Seasons:    []int{1},
			Episodes:   []int{7},
			Languages:  []string{"multi audio"},
			Resolution: "1080p",
			Quality:    "WEB-DL",
			Network:    "Amazon",
			Codec:      "h264",
			Dubbed:     true,
			Audio:      []string{"DDP", "Atmos"},
			Channels:   []string{"5.1"},
			// #Group: "K83",
			Site: "BEST-TORRENTS.COM",
		}},
		{"[ Torrent911.my ] The.Penguin.S01E07.FRENCH.WEBRip.x264.mp4", Result{
			Title:     "The Penguin",
			Seasons:   []int{1},
			Episodes:  []int{7},
			Languages: []string{"french"},
			Quality:   "WEBRip",
			Codec:     "x264",
			Site:      "Torrent911.my",
			Container: "mp4",
			Extension: "mp4",
		}},
		{"The.O.C.Seasons.01-04.AMZN.1080p.10bit.x265.hevc-Bearfish", Result{
			Title:      "The O C",
			Seasons:    []int{1, 2, 3, 4},
			Resolution: "1080p",
			Network:    "Amazon",
			Codec:      "hevc",
			BitDepth:   "10bit",
			Group:      "Bearfish",
		}},
		{"The Adam Project 2022 2160p NF WEB-DL DDP 5 1 Atmos DoVi HDR HEVC-SiC mkv", Result{
			Title:      "The Adam Project",
			Year:       "2022",
			Resolution: "4k",
			Quality:    "WEB-DL",
			Network:    "Netflix",
			Codec:      "hevc",
			Container:  "mkv",
			Audio:      []string{"Atmos", "DDP"},
			Channels:   []string{"5.1"},
			HDR:        []string{"DV", "HDR"},
		}},
		{"1923 S02E01 The Killing Season 1080p AMZN WEB-DL DDP5 1 H 264-FLUX[TGx]", Result{
			Title:      "1923",
			Seasons:    []int{2},
			Episodes:   []int{1},
			Resolution: "1080p",
			Quality:    "WEB-DL",
			Network:    "Amazon",
			Codec:      "h264",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Group:      "FLUX",
		}},
		{"1883.S01E01.1883.2160p.WEB-DL.DDP5.1.H.265-NTb.mkv", Result{
			Title:      "1883",
			Seasons:    []int{1},
			Episodes:   []int{1},
			Resolution: "4k",
			Quality:    "WEB-DL",
			Codec:      "h265",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Group:      "NTb",
			Extension:  "mkv",
			Container:  "mkv",
		}},
		{"1923 S02E01 1080p WEB H264-SuccessfulCrab", Result{
			Title:      "1923",
			Seasons:    []int{2},
			Episodes:   []int{1},
			Resolution: "1080p",
			Quality:    "WEB",
			Codec:      "h264",
			Group:      "SuccessfulCrab",
		}},
		{"[Anime Time] Naruto - 116 - 360 Degrees of Vision The Byakugan's Blind Spot.mkv", Result{
			Title:     "Naruto",
			Episodes:  []int{116},
			Group:     "Anime Time",
			Extension: "mkv",
			Container: "mkv",
		}},
		{"[DKB] Blue Lock - (Season 01) [1080p][HEVC x265 10bit][Multi-Subs]", Result{
			Title:      "Blue Lock",
			Seasons:    []int{1},
			Languages:  []string{"multi subs"},
			Resolution: "1080p",
			BitDepth:   "10bit",
			Codec:      "hevc",
			Subbed:     true,
			Group:      "DKB",
		}},
		{"Fallout.S01E03.The.Head.2160p.DV.HDR10Plus.Ai-Enhanced.H265.DDP.5.1.MULTI.RIFE.4.15v2-60fps-DirtyHippie.mkv", Result{
			Title:      "Fallout",
			Seasons:    []int{1},
			Episodes:   []int{3},
			Languages:  []string{"multi audio"},
			BitDepth:   "10bit",
			Resolution: "4k",
			Audio:      []string{"DDP"},
			Channels:   []string{"5.1"},
			Codec:      "h265",
			Container:  "mkv",
			Extension:  "mkv",
			Group:      "DirtyHippie",
			HDR:        []string{"DV", "HDR10+"},
			Upscaled:   true,
			Dubbed:     true,
		}},
		{"[JySzE] Naruto [v2] [R2J] [VFR] [Dual Audio] [Complete] [Extras] [x264]", Result{
			Title:     "Naruto",
			Languages: []string{"dual audio"},
			Codec:     "x264",
			Dubbed:    true,
			Group:     "JySzE",
			Complete:  true,
			Region:    "R2J",
		}},
		{"[JySzE] Naruto [v2] [R2J] [VFR] [Dual Audio] [Complete] [Extras] [x264]", Result{
			Title:     "Naruto",
			Languages: []string{"dual audio"},
			Codec:     "x264",
			Dubbed:    true,
			Group:     "JySzE",
			Complete:  true,
			Region:    "R2J",
		}},
		{"Naruto HD [1080p] (001-220) [Complete Series + Movies]", Result{
			Title:      "Naruto",
			Episodes:   intRange(1, 220),
			Resolution: "1080p",
			Quality:    "HDTV",
			Complete:   true,
		}},
		{"[JySzE] Naruto [v3] [R2J] [VFR] [Dual Audio] [Complete] [Extras] [x264]", Result{
			Title:     "Naruto",
			Languages: []string{"dual audio"},
			Codec:     "x264",
			Dubbed:    true,
			Group:     "JySzE",
			Complete:  true,
			Region:    "R2J",
		}},
		{"NARUTO CARTOON NETWORK-TOONAMI BROADCAST (2005-2009) [TVRip] [Episodes 001-209 Movies 1 & 3 & OVA)", Result{
			Title:    "NARUTO",
			Episodes: intRange(1, 209),
			Quality:  "TVRip",
			Complete: true,
			// "extras": ["OVA"],
			Network: "Cartoon Network",
			Year:    "2005-2009",
		}},
		{"NARUTO CARTOON NETWORK-TOONAMI BROADCAST (2005-2009) [TVRip] [Episodes 001-209 Movies 1 & 3 & OVA)", Result{
			Title:    "NARUTO",
			Episodes: intRange(1, 209),
			Quality:  "TVRip",
			Complete: true,
			// "extras": ["OVA"],
			Network: "Cartoon Network",
			Year:    "2005-2009",
		}},
		{"Naruto Complete [Ep 01 - 220][English][480p]", Result{ //# was incorrectly parsing episodes before
			Title:      "Naruto",
			Episodes:   intRange(1, 220),
			Languages:  []string{"english"},
			Complete:   true,
			Resolution: "480p",
		}},
		{"[DBD-Raws][火影忍者/Naruto/NARUTO -ナルト-][166-192TV][BOX7][美版/USA.Ver][1080P][BDRip][HEVC-10bit][FLAC][MKV]", Result{
			Title:      "Naruto",
			Episodes:   intRange(166, 192),
			Languages:  []string{"japanese", "chinese"},
			Quality:    "BDRip",
			Audio:      []string{"FLAC"},
			Resolution: "1080p",
			Codec:      "hevc",
			BitDepth:   "10bit",
			Container:  "mkv",
			Group:      "DBD-Raws",
		}},
		{"Naruto Collection [DB 1080p][ Dual Audio ][ English & Arabic Sub ]", Result{
			Title:      "Naruto",
			Languages:  []string{"dual audio", "english", "arabic"},
			Resolution: "1080p",
			Subbed:     true,
			Dubbed:     true,
			Complete:   true,
		}},
		{"Inherent.Vice.2014.1080p.BluRay.AVC.DTS-HD.MA.5.1-RARBG", Result{
			Title:      "Inherent Vice",
			Year:       "2014",
			Resolution: "1080p",
			Codec:      "avc",
			Audio:      []string{"DTS Lossless"},
			Channels:   []string{"5.1"},
			Group:      "RARBG",
			Quality:    "BluRay",
		}},
		{"Агентство / The Agency / Сезон: 1 / Серии: 1-10 из 10 [2024 HEVC HDR10 Dolby Vision WEB-DL 2160p 4k] MVO (HDRezka Studio) + DVO (Viruse Project) + Original + Sub (Eng)", Result{
			Title:      "The Agency",
			Seasons:    []int{1},
			Episodes:   intRange(1, 10),
			Languages:  []string{"english", "russian"},
			Quality:    "WEB-DL",
			Resolution: "4k",
			BitDepth:   "10bit",
			Codec:      "hevc",
			HDR:        []string{"DV", "HDR"},
			Subbed:     true,
			Year:       "2024",
			Group:      "Eng", // FIXME
		}},
	} {
		t.Run(tc.ttitle, func(t *testing.T) {
			result := Parse(tc.ttitle)
			assert.Equal(t, &tc.result, result)
		})
	}

	for _, tc := range []struct {
		ttitle string
		result Result
	}{
		{"[Golumpa] Fairy Tail - 214 [FuniDub 720p x264 AAC] [5E46AC39]", Result{
			Audio:       []string{"AAC"},
			Codec:       "x264",
			EpisodeCode: "5E46AC39",
			Episodes:    []int{214},
			Group:       "Golumpa",
			Resolution:  "720p",
			Title:       "Fairy Tail",
		}},
		{"The.Matrix.1999.1080p.BluRay.x264", Result{
			Codec:      "x264",
			Resolution: "1080p",
			Quality:    "BluRay",
			Title:      "The Matrix",
			Year:       "1999",
		}},
	} {
		t.Run(tc.ttitle, func(t *testing.T) {
			result := Parse(tc.ttitle)
			assert.Equal(t, &tc.result, result)
		})
	}
}
