package jackett

var indexerNameById = map[string]string{
	"0daykiev":               "0day.kiev",
	"0magnet":                "0Magnet",
	"1337x":                  "1337x",
	"13city":                 "13City",
	"1ptbar":                 "1ptbar",
	"3changtrai":             "3ChangTrai",
	"3dtorrents":             "3D Torrents",
	"4thd":                   "4thD",
	"52bt":                   "52BT",
	"52pt":                   "52PT",
	"pier720":                "720pier",
	"abnormal":               "Abnormal",
	"abtorrents":             "ABtorrents",
	"acgrip":                 "ACG.RIP",
	"acrossthetasman":        "Across The Tasman",
	"aftershock":             "Aftershock",
	"afun":                   "AFUN",
	"agsvpt":                 "AGSVPT",
	"aidoruonline":           "Aidoru!Online",
	"aither-api":             "Aither (API)",
	"alingpt":                "alingPT",
	"alpharatio":             "AlphaRatio",
	"amigosshare":            "Amigos Share Club",
	"anidub":                 "AniDUB",
	"anilibria":              "Anilibria",
	"animetosho":             "Anime Tosho",
	"animebytes":             "AnimeBytes",
	"animelayer":             "AnimeLayer",
	"animelovers-api":        "AnimeLovers (API)",
	"animetorrents":          "AnimeTorrents",
	"animetorrentsro":        "AnimeTorrents.ro",
	"animeworld-api":         "AnimeWorld (API)",
	"aniRena":                "AniRena",
	"anisource":              "AniSource",
	"anthelion-api":          "Anthelion (API)",
	"apachetorrent":          "ApacheTorrent",
	"arabafenice":            "ArabaFenice",
	"arabicsource":           "ArabicSource",
	"arabp2p":                "ArabP2P",
	"arabtorrents":           "ArabTorrents",
	"arenabg":                "ArenaBG",
	"asiancinema":            "AsianCinema",
	"asiandvdclub":           "AsianDVDClub",
	"audiences":              "Audiences",
	"audiobookbay":           "AudioBook Bay",
	"audionews":              "AudioNews",
	"aussierules":            "Aussierul.es",
	"avistaz":                "AvistaZ",
	"azusa":                  "Azusa (梓喵)",
	"backups":                "Back-ups",
	"bakabt":                 "BakaBT",
	"bangumi-moe":            "Bangumi Moe",
	"beload":                 "Beload",
	"bestcore":               "Best-Core",
	"best-torrents":          "Best-Torrents",
	"beyond-hd-api":          "Beyond-HD (API)",
	"bibliotik":              "Bibliotik",
	"bigcore":                "BigCore",
	"bigfangroup":            "BigFANGroup",
	"bitbazis":               "Bit-Bázis",
	"bithdtv":                "BIT-HDTV",
	"bitded":                 "Bitded",
	"bitgamer":               "bitGAMER",
	"bithumen":               "BitHUmen",
	"bitmagnet":              "BitMagnet (Local DHT)",
	"bitpalace":              "Bitpalace",
	"bitporn":                "BitPorn (API)",
	"bitru":                  "BitRu",
	"bitsearch":              "BitSearch",
	"bitsexy-api":            "BitSexy (API)",
	"Bittorrentfiles":        "Bittorrentfiles",
	"bitturk":                "BiTTuRK",
	"bjshare":                "BJ-Share",
	"bludv":                  "BluDV",
	"bluebirdhd":             "BlueBird",
	"blueroms":               "BlueRoms",
	"bluraytracker":          "BlurayTracker",
	"blutopia-api":           "Blutopia (API)",
	"booktracker":            "BookTracker",
	"bootytape":              "BootyTape",
	"borgzelle":              "Borgzelle",
	"boxingtorrents":         "Boxing Torrents",
	"brasiltracker":          "BrasilTracker",
	"broadcasthenet":         "BroadcasTheNet",
	"brokenstones":           "BrokenStones",
	"btetree":                "BT.etree",
	"btarg":                  "BTArg",
	"btdirectory":            "BTdirectory",
	"btnext":                 "BTNext",
	"btschool":               "BTSCHOOL",
	"btstate":                "btstate",
	"bwtorrents":             "BwTorrents",
	"byrbt":                  "BYRBT",
	"byrutor":                "Byrutor",
	"cspt":                   "Caishen (财神)",
	"cangbaoge":              "cangbaoge (CBG)",
	"capybarabr":             "CapybaraBR (API)",
	"carphunter":             "Carp-Hunter",
	"carpathians":            "Carpathians",
	"carpt":                  "CarPT",
	"cathoderaytube":         "Cathode-Ray.Tube",
	"catorrent":              "Catorrent",
	"cdfile":                 "CD File",
	"ceskeforum":             "CeskeForum",
	"cgpeers":                "CGPeers",
	"chdbits":                "CHDBits",
	"chilebt-api":            "ChileBT (API)",
	"cinecalidad":            "Cinecalidad",
	"cinemageddon":           "Cinemageddon",
	"cinemamovies":           "CinemaMovieS_ZT",
	"cinematik":              "Cinematik (API)",
	"cinemaz":                "CinemaZ",
	"clearjav-api":           "ClearJAV (API)",
	"coastalcrew":            "Coastal-Music-Crew",
	"comicat":                "comicat",
	"concen":                 "ConCen",
	"concertos":              "Concertos (API)",
	"cpasbienclone":          "cpasbien clone",
	"crabpt":                 "CrabPT (蟹黄堡)",
	"crackingpatching":       "CrackingPatching",
	"crazyspirits":           "CrazySpirits",
	"crnaberza":              "CrnaBerza",
	"crt2fa":                 "CRT2FA",
	"cyanbug":                "cyanbug (大青虫)",
	"damagnet":               "DaMagNet",
	"danishbytes-api":        "DanishBytes (API)",
	"darkpeers-api":          "Darkpeers (API)",
	"dasunerwartete":         "Das Unerwartete",
	"datascene-api":          "DataScene (API)",
	"deildu":                 "Deildu",
	"desitorrents-api":       "DesiTorrents (API)",
	"devil-torrents":         "Devil-Torrents",
	"diablotorrent":          "Diablo Torrent",
	"dicmusic":               "DICMusic",
	"digitalcore-api":        "DigitalCore (API)",
	"dimeadozen":             "DimeADozen",
	"discfan":                "DiscFan",
	"divxtotal":              "DivxTotal",
	"dmhy":                   "dmhy",
	"docspedia":              "DocsPedia",
	"dontorrent":             "DonTorrent",
	"dreamingtree":           "DreamingTree",
	"drugari":                "Drugari",
	"dxp":                    "DXP",
	"ehentai":                "E-Hentai",
	"ebookbay":               "EBookBay",
	"ebooks-shares":          "Ebooks-Shares",
	"electro-torrent":        "Electro-Torrent",
	"elitetorrent-wf":        "Elitetorrent-wf",
	"empornium":              "Empornium",
	"empornium2fa":           "Empornium2FA",
	"emuwarez":               "eMuwarez (API)",
	"epublibre":              "EpubLibre",
	"erai-raws":              "Erai-Raws",
	"esharenet":              "eShareNet",
	"estone":                 "eStone",
	"ex-torrenty":            "Ex-torrenty",
	"exitorrent-org":         "exitorrent.org",
	"exkinoray":              "ExKinoRay",
	"exoticaz":               "ExoticaZ",
	"explosiv-world":         "Explosiv-World",
	"extratorrent-st":        "ExtraTorrent.st",
	"extremebits":            "ExtremeBits",
	"eztv":                   "EZTV",
	"eztvl":                  "EZTVL",
	"f1carreras-api":         "F1Carreras (API)",
	"f1gp":                   "F1GP",
	"fanoin":                 "FANO.IN",
	"fappaizuri":             "Fappaizuri",
	"fearnopeer":             "FearNoPeer",
	"femdomcult":             "Femdomcult",
	"fenyarnyek-tracker":     "Fenyarnyek-Tracker",
	"file-tracker":           "File-Tracker",
	"filelist":               "FileList",
	"filemood":               "FileMood",
	"filmeshdtorrent":        "Filmes HD Torrent",
	"finelite":               "FinElite",
	"flood":                  "Flood",
	"fluxzone":               "Flux-Zone",
	"freefarm":               "Free Farm (自由农场)",
	"freejavtorrent":         "Free JAV Torrent",
	"frozenlayer":            "Frozen Layer",
	"funfile":                "FunFile",
	"funkytorrents":          "FunkyTorrents",
	"futuretorrent":          "FutureTorrent",
	"fuzer":                  "Fuzer",
	"gamestorrents":          "GamesTorrents",
	"gay-torrents":           "Gay-Torrents.net",
	"gay-torrentsorg":        "gay-torrents.org",
	"gaytorrentru":           "GAYtorrent.ru",
	"gazellegamesapi":        "GazelleGames (API)",
	"generationfree-api":     "Generation-Free (API)",
	"ggpt":                   "GGPT",
	"gigatorrents":           "GigaTorrents",
	"gimmepeers":             "GimmePeers",
	"girotorrent":            "Girotorrent",
	"greatposterwall":        "GreatPosterWall",
	"gtorrentpro":            "GTorrent.club",
	"haidan":                 "HaiDan",
	"haitang":                "Hǎitáng (海棠PT)",
	"happyfappy":             "HappyFappy",
	"happyfappy2fa":          "HappyFappy2FA",
	"hawke-uno":              "hawke-uno",
	"hddolby":                "HD Dolby",
	"hd-club":                "HD-CLUB",
	"hdcztorrent":            "HD-CzTorrent",
	"hdforever":              "HD-Forever",
	"hdolimpo-api":           "HD-Olimpo (API)",
	"hdonly-api":             "HD-Only (API)",
	"hdspace":                "HD-Space",
	"hdtorrents":             "HD-Torrents",
	"hd-unit3d-api":          "HD-UNiT3D (API)",
	"hdarea":                 "HDArea",
	"hdbao":                  "HDBao",
	"hdbitsapi":              "HDBits (API)",
	"hdc":                    "HDCiTY",
	"hdclone":                "HDClone",
	"hdfans":                 "HDFans",
	"hdgalaktik":             "HDGalaKtik",
	"hdhome":                 "HDHome",
	"hdkylin":                "HDKylin (麒麟)",
	"hdroute":                "HDRoute",
	"hdrtorrent":             "HDRTorrent",
	"hdsky":                  "HDSky",
	"hdtime":                 "HDtime",
	"hdtorrentsit":           "HDTorrents.it (API)",
	"hdturk":                 "HDTurk",
	"hdu":                    "HDU",
	"hdzero-api":             "HDZero (API)",
	"hebits":                 "Hebits",
	"hellashut":              "HellasHut",
	"hellashut-api":          "HellasHut (API)",
	"hellenic-hd-api":        "HELLENIC-HD (API)",
	"helltorrents":           "HellTorrents",
	"hhanclub":               "HHanClub",
	"hhd-api":                "HHD (API)",
	"homeporntorrents":       "HomePornTorrents",
	"houseofdevil":           "House of Devil",
	"hqmusic":                "HQMusic",
	"hudbt":                  "HUDBT (蝴蝶)",
	"huntorrent":             "HunTorrent",
	"idope":                  "iDope",
	"ilcorsaroblu":           "Il Corsaro Blu",
	"ilcorsaronero":          "ilCorSaRoNeRo",
	"ildragonero":            "ilDraGoNeRo",
	"ilolicon":               "ilolicon PT",
	"immortalseed":           "ImmortalSeed",
	"immortuos":              "Immortuos",
	"indietorrents":          "Indietorrents",
	"infinity-api":           "INFINITY (API)",
	"infire":                 "Infire",
	"insanetracker":          "Insane Tracker",
	"internetarchive":        "Internet Archive",
	"iptorrents":             "IPTorrents",
	"isohunt2":               "Isohunt2",
	"itatorrents":            "ItaTorrents",
	"jme-reunit3d-api":       "JME-REUNIT3D (API)",
	"joyhd":                  "JoyHD",
	"jpopsuki":               "JPopsuki",
	"kamept":                 "KamePT",
	"karagarga":              "Karagarga",
	"keepfriends":            "Keep Friends",
	"kelu":                   "Kelu",
	"kickasstorrents-to":     "kickasstorrents.to",
	"kickasstorrents-ws":     "kickasstorrents.ws",
	"kinorun":                "Kinorun",
	"kinozal":                "Kinozal",
	"kinozal-magnet":         "Kinozal (M)",
	"knaben":                 "Knaben",
	"korsar":                 "Korsar",
	"krazyzone":              "KrazyZone",
	"kufei":                  "Kufei (库非)",
	"kufirc":                 "Kufirc",
	"kufirc2fa":              "Kufirc2FA",
	"lajidui":                "lajidui",
	"lastdigitalunderground": "Last Digital Underground",
	"lastfiles":              "LastFiles",
	"lat-team-api":           "Lat-Team (API)",
	"learnflakes":            "LearnFlakes",
	"leech24":                "leech24",
	"lemonhd":                "LemonHD",
	"lesaloon":               "LeSaloon",
	"lesbians4u":             "Lesbians4u",
	"letseed":                "LetSeed",
	"libble":                 "Libble",
	"libranet":               "LibraNet",
	"limetorrents":           "LimeTorrents",
	"linkomanija":            "LinkoManija",
	"linuxtracker":           "LinuxTracker",
	"locadora":               "Locadora (API)",
	"losslessclub":           "LosslessClub",
	"lostfilm":               "LostFilm.tv",
	"lst":                    "LST",
	"luckpt":                 "LuckPT",
	"mteamtp":                "M-Team - TP",
	"mactorrentsdownload":    "Mac Torrents Download",
	"madsrevolution":         "MaDs Revolution",
	"magnetcat":              "Magnet Cat",
	"magnetdownload":         "MagnetDownload",
	"magnetico":              "Magnetico (Local DHT)",
	"majomparade":            "Majomparádé",
	"makingoff":              "Making Off",
	"malayabits-api":         "Malayabits (API)",
	"marinetracker":          "Marine Tracker",
	"masters-tb":             "Masters-TB",
	"matrix":                 "Matrix",
	"mazepa":                 "Mazepa",
	"mdan":                   "MDAN",
	"megamixtracker":         "MegamixTracker",
	"megapeer":               "MegaPeer",
	"mejortorrent":           "MejorTorrent",
	"mesevilag":              "MeseVilág",
	"metaltracker":           "Metal Tracker",
	"metalguru":              "MetalGuru",
	"mikan":                  "Mikan",
	"milkie":                 "Milkie",
	"miobt":                  "MioBT",
	"mircrew":                "MIRCrew",
	"mixtapetorrent":         "MixtapeTorrent",
	"mma-torrents":           "MMA-torrents",
	"mnv":                    "MNV",
	"mojblink":               "MOJBLiNK",
	"monikadesign-api":       "MonikaDesign (API)",
	"morethantv-api":         "MoreThanTV (API)",
	"mousebits":              "MouseBits",
	"moviesdvdr":             "MoviesDVDR",
	"musebootlegs":           "MuseBootlegs",
	"mvgroupforum":           "MVGroup Forum",
	"mvgroupmain":            "MVGroup Main",
	"myanonamouse":           "MyAnonamouse",
	"mypornclub":             "MyPornClub",
	"myspleen":               "MySpleen",
	"ncore":                  "nCore",
	"nebulanceapi":           "NebulanceAPI",
	"nethd":                  "NetHD",
	"newheaven":              "New Heaven",
	"newstudio":              "NewStudio",
	"newstudiol":             "NewStudioL",
	"nicept":                 "NicePT",
	"nipponsei":              "Nipponsei",
	"nirvana":                "Nirvana (API)",
	"noname-club":            "NoNaMe Club",
	"noname-clubl":           "NoNaMe ClubL",
	"norbits":                "NorBits",
	"nordicquality-api":      "NordicQuality (API)",
	"nortorrent":             "NorTorrent",
	"nusantarare":            "Nusanta(RA.RE)",
	"nyaasi":                 "Nyaa.si",
	"okpt":                   "OKPT",
	"oldgreektracker":        "Old Greek Tracker (OGT)",
	"oldtoonsworld":          "OldToonsWorld (API)",
	"onejav":                 "OneJAV",
	"onlyencodes-api":        "OnlyEncodes+ (API)",
	"opencd":                 "OpenCD",
	"opensharing":            "OpenSharing",
	"orpheus":                "Orpheus",
	"oshenpt":                "OshenPT",
	"ourbits":                "OurBits",
	"oxtorrent-co":           "OxTorrent",
	"oxtorrent-vip":          "OxTorrent-vip",
	"p2pbg":                  "P2PBG",
	"panda":                  "Panda",
	"party-tracker":          "Party-Tracker",
	"passthepopcorn":         "PassThePopcorn",
	"pctorrent":              "PC-torrent",
	"peeratiko":              "Peeratiko",
	"peersfm":                "Peers.FM",
	"pignetwork":             "PigNetwork (猪猪网)",
	"piratesparadise":        "Pirate's Paradise",
	"pixelcove":              "PixelCove",
	"pixelcove2fa":           "PixelCove2FA",
	"pixelhd":                "PiXELHD",
	"plugintorrent":          "plugintorrent",
	"polishtorrent":          "Polish Torrent (API)",
	"polishtracker-api":      "PolishTracker (API)",
	"polskie-torrenty":       "Polskie-Torrenty",
	"pornbay":                "Pornbay",
	"pornolab":               "PornoLab",
	"pornotorrent":           "PornoTorrent",
	"pornrips":               "PornRips",
	"portugas-api":           "Portugas (API)",
	"postman":                "Postman",
	"postman-api":            "Postman (API)",
	"pretome":                "PreToMe",
	"privatehd":              "PrivateHD",
	"proaudiotorrents":       "ProAudioTorrents",
	"proporno":               "ProPorno",
	"ptgtk":                  "PT GTK",
	"ptcafe":                 "PTCafe (咖啡)",
	"ptchina":                "PTChina (铂金学院)",
	"pterclub":               "PTerClub (PT之友俱乐部)",
	"ptfans":                 "PTFans",
	"ptfiles":                "PTFiles",
	"pthome":                 "PThome",
	"ptsbao":                 "PTSBAO (烧包)",
	"ptskit":                 "PTSKIT",
	"pttime":                 "PTTime",
	"ptvicomo":               "PTVicomo",
	"ptitzmx":                "PT分享站 (itzmx)",
	"punkshorror":            "Punk's Horror Tracker",
	"puntotorrent":           "PuntoTorrent",
	"pussytorrents":          "PussyTorrents",
	"putao":                  "PuTao (葡萄)",
	"pwtorrents":             "PWTorrents",
	"qbite":                  "Qbite (Hubite)",
	"qingwa":                 "Qingwa (青蛙)",
	"r3vwtf":                 "R3V WTF!",
	"racing4everyone-api":    "Racing4Everyone (API)",
	"racingforme":            "RacingForMe",
	"railgunpt":              "RailgunPT",
	"rain":                   "Rain (雨)",
	"rainbowtracker":         "Rainbow Tracker",
	"rastastugan-api":        "Rastastugan (API)",
	"redstartorrent":         "Red Star Torrent",
	"redacted":               "Redacted",
	"redetorrent":            "RedeTorrent",
	"reelflix-api":           "ReelFLiX (API)",
	"retroflix":              "RetroFlix",
	"revolutiontt":           "RevolutionTT",
	"rgfootball":             "RGFootball",
	"rintor":                 "RinTor",
	"rintornet":              "RinTor.NeT",
	"riperam":                "RiperAM",
	"RockBox":                "RockBox",
	"rockethd":               "RocketHD (API)",
	"romanianmetaltorrents":  "Romanian Metal Torrents",
	"rousi":                  "Rousi",
	"rudub":                  "RUDUB",
	"rustorka":               "Rustorka",
	"rutor":                  "RuTor",
	"rutracker":              "RuTracker.org",
	"rutracker-ru":           "RuTracker.RU",
	"samaritano":             "SAMARITANO (API)",
	"sbpt":                   "SBPT",
	"scenehd":                "SceneHD",
	"scenerush":              "SceneRush",
	"scenetime":              "SceneTime",
	"secretcinema":           "Secret Cinema",
	"seedfile":               "SeedFile",
	"seedpool-api":           "seedpool (API)",
	"selezen":                "seleZen",
	"sewerpt":                "SewerPT",
	"sexypics":               "Sexy-Pics",
	"sfp":                    "SFP",
	"shakaw":                 "ShaKaw",
	"shanaproject":           "Shana Project",
	"shareisland-api":        "Shareisland (API)",
	"sharewood-api":          "Sharewood (API)",
	"shazbat":                "Shazbat",
	"showrss":                "showRSS",
	"siambit":                "SiamBIT",
	"skidrowrepack":          "SkidrowRepack",
	"skipthecommercials-api": "SkipTheCommercials (API)",
	"sktorrent":              "SkTorrent",
	"sktorrent-org":          "SkTorrent.org",
	"snowpt":                 "SnowPT",
	"sosulki":                "sosulki",
	"soulvoice":              "SoulVoice (聆音Club)",
	"speedcd":                "Speed.cd",
	"speedapp":               "SpeedApp",
	"speedmasterhd":          "Speedmaster HD",
	"spiritofrevolution":     "Spirit of Revolution",
	"sportscult":             "SportsCult",
	"springsunday":           "SpringSunday",
	"subsplease":             "SubsPlease",
	"sugoimusic":             "SugoiMusic",
	"sukebeinyaasi":          "sukebei.nyaa.si",
	"superbits":              "Superbits",
	"swarmazon-api":          "Swarmazon (API)",
	"tangmen":                "Tangmen (唐门)",
	"tapochek":               "Tapochek",
	"tasmanit":               "Tasmanit",
	"teamctgame":             "Team CT Game",
	"teamhd":                 "TeamHD",
	"teamos":                 "TeamOS",
	"tekno3d":                "TEKNO3D",
	"thecrazyones":           "The Crazy Ones",
	"theempire":              "The Empire",
	"thefallingangels":       "The Falling Angels",
	"thegeeks":               "The Geeks",
	"thekitchen":             "The Kitchen",
	"newretro":               "The New Retro",
	"theoccult":              "The Occult",
	"theoldschool-api":       "The Old School (API)",
	"theparadiese":           "The Paradiese",
	"thepiratebay":           "The Pirate Bay",
	"theplace":               "The Place",
	"theshow":                "The Show",
	"thevault":               "The Vault",
	"thenewfun":              "The-New-Fun",
	"theleachzone-api":       "TheLeachZone (API)",
	"themixingbowl":          "themixingbowl",
	"thepiratedship":         "ThePiratedShip",
	"therarbg":               "TheRARBG",
	"tjupt":                  "TJUPT (北洋园PT)",
	"tlfbits":                "TLFBits",
	"tmghub":                 "TmGHuB",
	"tocashare":              "Toca Share (API)",
	"tokyotosho":             "Tokyo Toshokan",
	"toloka":                 "Toloka.to",
	"tormac":                 "Tormac",
	"tornado":                "Tornado",
	"torrentdownloads":       "Torrent Downloads",
	"torrent-heaven":         "Torrent Heaven",
	"torrentnetwork":         "Torrent Network",
	"torrentoyunindir":       "Torrent Oyun indir",
	"torrenttrader":          "Torrent Trader",
	"torrent-pirat":          "torrent-pirat",
	"torrentsyndikat":        "Torrent-Syndikat",
	"torrent-turk":           "TOrrent-tuRK",
	"torrentby":              "torrent.by",
	"torrentlt":              "Torrent.LT",
	"torrentcore":            "Torrent[CORE]",
	"torrent9":               "Torrent9",
	"torrentbd":              "TorrentBD",
	"torrentbytes":           "TorrentBytes",
	"torrentccf":             "TorrentCCF",
	"torrentcontrol":         "TorrentControl (API)",
	"torrentday":             "TorrentDay",
	"torrentdd":              "TorrentDD",
	"torrentdosfilmes":       "TorrentDosFilmes",
	"torrentdownload":        "TorrentDownload",
	"torrenteros-api":        "Torrenteros (API)",
	"torrentgalaxyclone":     "TorrentGalaxyClone",
	"torrenthr":              "TorrentHR",
	"torrenting":             "Torrenting",
	"torrentkitty":           "TorrentKitty",
	"torrentleech":           "TorrentLeech",
	"torrentleech-pl":        "Torrentleech.pl",
	"torrentmasters":         "TorrentMasters",
	"torrentproject2":        "TorrentProject2",
	"torrentqq":              "TorrentQQ",
	"torrentscsv":            "Torrents.csv",
	"torrentsir":             "TorrentSir",
	"torrentsome":            "Torrentsome",
	"torrentssg":             "torrentssg",
	"torrenttip":             "Torrenttip",
	"totheglory":             "ToTheGlory",
	"totheglory2fa":          "ToTheGlory2FA",
	"trackermk":              "TrackerMK",
	"traht":                  "TrahT",
	"trancetraffic":          "TranceTraffic",
	"trellas":                "Trellas",
	"trezzor":                "TreZzoR",
	"trezzorcookie":          "TreZzoRCookie",
	"tribalmixes":            "TribalMixes",
	"turkseed-api":           "TurkSeed (API)",
	"turktorrent":            "TurkTorrent",
	"tvstore":                "TV Store",
	"tvchaosuk":              "TVChaosUK",
	"u2":                     "U2",
	"u3c3":                   "U3C3",
	"ubits":                  "UBits",
	"uhdbits":                "UHDBits",
	"uhdtorrent":             "uHDTorrent",
	"uindex":                 "Uindex",
	"ultrahd":                "UltraHD",
	"unionfansub":            "Union Fansub",
	"uniotaku":               "UniOtaku",
	"unlimitz":               "Unlimitz",
	"uploadcx":               "upload.cx (API)",
	"upscalevault-api":       "Upscale Vault (API)",
	"utopia":                 "UTOPIA (API)",
	"uztracker":              "UzTracker",
	"vault-network":          "Vault network",
	"videoteka":              "ViDEOTEKA",
	"vsttorrents":            "VST Torrentz",
	"vsthouse":               "VSTHouse",
	"vstorrent":              "VSTorrent",
	"wdt":                    "WDT",
	"whiteangel":             "White Angel",
	"wintersakura":           "WinterSakura",
	"wolfmax4k":              "Wolfmax 4k",
	"wihd":                   "World-In-HD",
	"world-of-tomorrow":      "World-of-Tomorrow",
	"xiteme":                 "x-ite.me",
	"xspeeds":                "XSpeeds",
	"xthor-api":              "Xthor (API)",
	"xtorrenty":              "xTorrenty",
	"xtremebytes":            "Xtreme Bytes",
	"xwtclassics":            "XWT-Classics",
	"xwtorrents":             "XWtorrents",
	"xxxclub":                "XXXClub",
	"xxxtor":                 "xxxtor",
	"yggcookie":              "YGG cookie",
	"yggtorrent":             "YggTorrent",
	"yoinked":                "YOiNKED (API)",
	"yts":                    "YTS",
	"yuscene-api":            "YUSCENE (API)",
	"zamundanet":             "Zamunda.net",
	"zappateers":             "Zappateers",
	"zelkaorg":               "Zelka.org",
	"zetorrents":             "zetorrents",
	"zktorrent":              "ZkTorrent",
	"zmpt":                   "ZmPT (织梦)",
	"zonaq":                  "ZonaQ",
	"ztracker":               "Ztracker",
}

func GetIndexerName(id string) string {
	name, ok := indexerNameById[id]
	if !ok {
		return id
	}
	return name
}
